import base64
import json
import logging
import os
from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from backend.config import BASE_DIR, MODELS_DIR
from backend.llm.explainer import generate_explanation
from backend.models.predictor import HybridPredictor

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Social Media Performance Predictor",
    description="Predicts Instagram post engagement for beverage brands.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global predictor instance — loaded once at startup
_predictor: Optional[HybridPredictor] = None


@app.on_event("startup")
async def startup():
    global _predictor
    model_path = MODELS_DIR / "hybrid_predictor.joblib"
    if model_path.exists():
        logger.info("Loading trained model …")
        _predictor = HybridPredictor.load(model_path)
        logger.info("Model ready.")
    else:
        logger.warning(
            "No trained model found at %s — run `python train.py` first.", model_path
        )


def _get_predictor() -> HybridPredictor:
    if _predictor is None:
        raise HTTPException(
            status_code=503,
            detail="Model not loaded. Run `python train.py` first, then restart the server.",
        )
    return _predictor


# ------------------------------------------------------------------
# Static frontend
# ------------------------------------------------------------------

_frontend_dir = BASE_DIR / "frontend"
if _frontend_dir.exists():
    app.mount("/static", StaticFiles(directory=str(_frontend_dir)), name="static")


@app.get("/", include_in_schema=False)
async def serve_frontend():
    index = _frontend_dir / "index.html"
    if index.exists():
        return FileResponse(str(index))
    return {"message": "API is running. See /docs for the API reference."}


# ------------------------------------------------------------------
# Health & metadata
# ------------------------------------------------------------------

@app.get("/health", tags=["meta"])
async def health():
    return {"status": "ok", "model_loaded": _predictor is not None}


@app.get("/brands", tags=["meta"])
async def list_brands():
    """Return all brands the model knows about."""
    if _predictor is None:
        from backend.config import KNOWN_BRANDS
        return {"brands": KNOWN_BRANDS}
    brands = sorted(b for b in _predictor.brand_stats if not b.startswith("_"))
    return {"brands": brands}


@app.get("/api/dataset/stats", tags=["meta"])
async def dataset_stats():
    """Per-brand engagement statistics derived from the training dataset."""
    p = _get_predictor()
    out = {}
    for brand, stats in p.brand_stats.items():
        if brand.startswith("_"):
            continue
        out[brand] = {
            "n_posts": stats.get("n_posts"),
            "median_engagement_rate": round(stats.get("median", 0), 2),
            "mean_engagement_rate": round(stats.get("mean", 0), 2),
            "p33_engagement_rate": round(stats.get("p33", 0), 2),
            "p67_engagement_rate": round(stats.get("p67", 0), 2),
        }
    return {"brand_stats": out}


@app.get("/api/evaluation", tags=["evaluation"])
async def get_evaluation():
    """Return pre-computed evaluation results (generated by train.py)."""
    eval_path = MODELS_DIR / "evaluation_results.json"
    if not eval_path.exists():
        raise HTTPException(
            status_code=404,
            detail="Evaluation results not found. Run `python train.py` first.",
        )
    with open(eval_path) as f:
        return json.load(f)


# ------------------------------------------------------------------
# Prediction — JSON body
# ------------------------------------------------------------------

class PredictRequest(BaseModel):
    caption: str
    brand: str
    media_type: str = "reel"                         # reel | post | album
    duration: Optional[int] = None                   # seconds (reels only)
    is_collaborated: bool = False
    collaborators: Optional[List[str]] = []
    collaborator_follower_count: Optional[int] = None  # used for tier-based score boost
    posted_at: Optional[str] = None                  # ISO-8601 datetime string
    visual_summary: Optional[str] = None
    followers: Optional[int] = None                  # override brand default


class SeedPost(BaseModel):
    caption: str
    engagement_rate: float
    media_type: str = "reel"
    duration: Optional[int] = None
    is_collaborated: bool = False
    collaborators: Optional[List[str]] = []
    created_at: Optional[str] = None
    visual_summary: Optional[str] = None


class RegisterBrandRequest(BaseModel):
    brand: str
    followers: int
    seed_posts: List[SeedPost]


@app.post("/api/predict", tags=["prediction"])
async def predict_json(request: PredictRequest):
    """
    Predict engagement for a new post draft.

    - **caption**: Post caption text (required)
    - **brand**: Brand username, e.g. `cocacola_india` (required)
    - **media_type**: `reel` | `post` | `album` (default: `reel`)
    - **duration**: Video length in seconds (reels only)
    - **is_collaborated**: Whether the post is a collab
    - **collaborators**: List of collaborator usernames
    - **collaborator_follower_count**: Follower count of the main collaborator (enables tier-based score boost)
    - **posted_at**: Planned publish time (ISO-8601); affects time-of-day features
    - **visual_summary**: Text description of the creative (from a vision model or manual)
    - **followers**: Override the brand's default follower count
    """
    p = _get_predictor()
    post = _build_post_dict(request)
    try:
        result = p.predict(post)
        result = await _enrich_explanation(post, result, p)
        return result
    except Exception as exc:
        logger.exception("Prediction error")
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/brands/register", tags=["brands"])
async def register_brand(request: RegisterBrandRequest):
    """
    Register a new brand (cold-start) or add seed posts to an existing one.

    Provide at least 10 real posts with their actual engagement rates to get
    meaningful within-brand predictions. With fewer posts, cross-brand similarity
    dominates and accuracy is lower.

    After registration, the model is saved to disk automatically.
    """
    p = _get_predictor()
    if len(request.seed_posts) < 3:
        raise HTTPException(
            status_code=422,
            detail="At least 3 seed posts are required. Provide 10+ for best results.",
        )
    try:
        seed_dicts = [sp.model_dump() for sp in request.seed_posts]
        result = p.add_brand(request.brand, request.followers, seed_dicts)
        return {
            "status": "registered",
            **result,
            "message": (
                f"Brand '{request.brand}' registered with {len(request.seed_posts)} posts. "
                "Predictions for this brand will now use within-brand similarity."
            ),
        }
    except Exception as exc:
        logger.exception("Brand registration error")
        raise HTTPException(status_code=500, detail=str(exc))


# ------------------------------------------------------------------
# Prediction — multipart form (with optional image upload)
# ------------------------------------------------------------------

@app.post("/api/predict/upload", tags=["prediction"])
async def predict_upload(
    caption: str = Form(...),
    brand: str = Form(...),
    media_type: str = Form("reel"),
    duration: Optional[int] = Form(None),
    is_collaborated: bool = Form(False),
    collaborators: str = Form(""),
    collaborator_follower_count: Optional[int] = Form(None),
    posted_at: Optional[str] = Form(None),
    visual_summary: Optional[str] = Form(None),
    image: Optional[UploadFile] = File(None),
):
    """
    Same as `/api/predict` but accepts `multipart/form-data` so the frontend
    can upload a creative image directly.  If an image is provided and no
    `visual_summary` is supplied, the system will attempt to describe it via
    the OpenAI Vision API (requires `OPENAI_API_KEY` in env).
    """
    p = _get_predictor()

    img_summary = visual_summary or ""
    if image and not img_summary:
        try:
            img_summary = await _vision_summary(image)
        except Exception as exc:
            logger.warning("Vision summary failed: %s", exc)
            img_summary = ""

    collab_list = [c.strip() for c in collaborators.split(",") if c.strip()]

    post = {
        "caption": caption,
        "brand": brand,
        "media_type": media_type,
        "duration": duration,
        "is_collaborated": is_collaborated or bool(collab_list),
        "collaborators": collab_list,
        "num_collaborators": len(collab_list),
        "collaborator_follower_count": collaborator_follower_count,
        "created_at": posted_at,
        "visual_summary": img_summary,
        "followers": p.brand_stats.get(brand, {}).get("median_followers", 100_000),
    }

    try:
        result = p.predict(post)
        result = await _enrich_explanation(post, result, p)
        result["visual_summary_used"] = img_summary
        return result
    except Exception as exc:
        logger.exception("Prediction error")
        raise HTTPException(status_code=500, detail=str(exc))


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------

async def _enrich_explanation(post: dict, result: dict, p: HybridPredictor) -> dict:
    """
    Replace the template explanation summary with an LLM-generated one when
    OPENAI_API_KEY is set. Falls back gracefully; never blocks the prediction.
    """
    try:
        exp = result.get("explanation", {})
        brand = post.get("brand", "unknown")
        brand_stats = p.brand_stats.get(brand) or p.brand_stats.get("_global", {})
        alignment = result.get("model_details", {}).get("brand_alignment_score")
        llm_summary = await generate_explanation(
            post=post,
            prediction=result,
            similar_posts=exp.get("similar_posts", []),
            key_factors=exp.get("key_factors", []),
            brand_stats=brand_stats,
            brand_alignment_score=alignment,
        )
        result["explanation"]["summary"] = llm_summary
    except Exception as e:
        logger.warning("Explanation enrichment failed: %s", e)
    return result


def _build_post_dict(req: PredictRequest) -> dict:
    p = _get_predictor()
    collab_list = req.collaborators or []
    return {
        "caption": req.caption,
        "brand": req.brand,
        "media_type": req.media_type,
        "duration": req.duration,
        "is_collaborated": req.is_collaborated or bool(collab_list),
        "collaborators": collab_list,
        "num_collaborators": len(collab_list),
        "collaborator_follower_count": req.collaborator_follower_count,
        "created_at": req.posted_at,
        "visual_summary": req.visual_summary or "",
        "followers": req.followers or p.brand_stats.get(req.brand, {}).get("median_followers", 100_000),
    }


async def _vision_summary(image: UploadFile) -> str:
    """Call OpenAI GPT-4o-mini Vision to describe the uploaded creative."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return ""

    from openai import AsyncOpenAI

    contents = await image.read()
    b64 = base64.b64encode(contents).decode()
    mime = image.content_type or "image/jpeg"

    client = AsyncOpenAI(api_key=api_key)
    resp = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "Analyze this Instagram post image briefly. Provide: "
                            "1) Summary 2) Any visible text 3) Visual entities "
                            "4) Brand logos if visible. Keep it under 200 words."
                        ),
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:{mime};base64,{b64}"},
                    },
                ],
            }
        ],
        max_tokens=250,
    )
    return resp.choices[0].message.content or ""
